[[listen]]
type = "tcp"
address = "0.0.0.0:5353"

[[listen]]
type = "udp"
address = "0.0.0.0:5353"

[[upstreams]]
name = "google"
address = "https://dns.google.com/resolve"
method = "doh-json"

[[upstreams]]
name = "cloudflare"
address = "https://1.1.1.1/dns-query"
method = "doh-wireformat"

[[upstreams]]
name = "cloudflare-tcp"
address = "1.1.1.1:53"
method = "tcp"

[[upstreams]]
name = "aliyun"
address = "223.5.5.5:53"
method = "udp"

[[rules]]
name = "iplist:ip.txt"
upstream = "aliyun"

[[rules]]
name = "group:block"
action = "reject"

[[rules]]
name = "group:gfwlist"
upstream = "cloudflare"

[[rules]]
name = "fqdn:dns.google.com"
upstream = "cloudflare"

[[rules]]
name = "other"
upstream = "cloudflare"

[Groups.block]
list = []

[Groups.gfwlist]
list = []

[[records]]
name = "suffix:.onion"
type = "A"
ttl = 3600
context = "127.0.0.1"
